let flights = [
    {
        id:0,
        flightNum:75485,
        departureFlight:"israel",
        flightLanding:"paradise",
        seatNum:75,
        departureTime:"14:45",
        LandingTime:"15:30",
        firstClass:true
    },
    {
        id:1,
        flightNum:12457,
        departureFlight:"mexico",
        flightLanding:"laos",
        seatNum:50,
        departureTime:"20:50",
        LandingTime:"07:20",
        firstClass:true
    },
    {
        id:2,
        flightNum:789687,
        departureFlight:"sri-Lanka",
        flightLanding:"india",
        seatNum:24,
        departureTime:"18:45",
        LandingTime:"22:30",
        firstClass:false
    },
    {
        id:3,
        flightNum:25257,
        departureFlight:"ethiopia",
        flightLanding:"brazil",
        seatNum:20,
        departureTime:"18:45",
        LandingTime:"17:10",
        firstClass:true
    },
]

module.exports = flights